---
title: "High Resolution Mapping of Soil Properties"
author: "Ozias Hounkpatin"
date: "2025-04-25"
output: html_document
---

# Introduction

Six soil properties- sand, silt, clay, cation exchange capacity, soil organic carbon, nitrogen were predicted using remote sensing data in the Dano Catchment (West Africa, Burkina Faso) and machine learning models. The example R code is in support  of the article entitled: "High resolution mapping of soil properties using remote sensing variables in south-western Burkina Faso: a comparison of machine learning and multiple linear regression models".

Forkuor, G., Hounkpatin, O.K., Welp, G. and Thiel, M., 2017. High resolution mapping of soil properties using remote sensing variables in south-western Burkina Faso: a comparison of machine learning and multiple linear regression models. PloS one, 12(1), p.e0170478.

# Full data 
In the data folder are the excel files for the data catchment as well as that of the extrapolation area. The full dataset used for the prediction can be acessed via this link:https://figshare.com/s/abe41649a5b3c5950372 
The uploaded datasets include the following: (1) The dataset used for the present manuscript as well as the R code, (2)The maps related to the topographical and climatic variables, (3) The maps related to Landsat variables, (4) the shapefile containing all data points for each soil property.